# Generated by Django 5.2.18 on 2026-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '班級', 'verbose_name_plural': '班級'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': '班級成員', 'verbose_name_plural': '班級成員'},
        ),
    ]
