# Generated by Django 5.2.18 on 2026-10-08 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('cleared', '通關'), ('failed', 'Game Over'), ('abandoned', '中途離開')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_seq', models.PositiveIntegerField(default=0, verbose_name='已處理的最後事件序號')),
                ('answer_score', models.IntegerField(blank=True, null=True)),
                ('battle_score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('is_first_clear', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='games.gamelevel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='learning.gamesession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=40, verbose_name='玩家選的選項')),
                ('is_correct', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='games.question')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.learningrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', '-started_at'], name='session_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game', 'status'], name='session_game_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='session_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'game'), name='session_single_in_progress'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['level', 'completed_at'], name='record_level_done_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningrecord',
            constraint=models.UniqueConstraint(fields=('session', 'level'), name='record_unique_level_per_session'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['question', 'is_correct'], name='attempt_question_result_idx'),
        ),
    ]
