# Generated by Django 5.2.18 on 2026-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_fix_abandoned_session_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': '遊玩紀錄', 'verbose_name_plural': '遊玩紀錄'},
        ),
        migrations.AlterModelOptions(
            name='learningrecord',
            options={'ordering': ['-started_at'], 'verbose_name': '關卡紀錄', 'verbose_name_plural': '關卡紀錄'},
        ),
        migrations.AlterModelOptions(
            name='questionattempt',
            options={'verbose_name': '遊戲作答', 'verbose_name_plural': '遊戲作答'},
        ),
        migrations.AlterModelOptions(
            name='reviewattempt',
            options={'verbose_name': '複習作答', 'verbose_name_plural': '複習作答'},
        ),
    ]
