# Generated by Django 5.2.18 on 2026-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='老師'),
        ),
    ]
