# Generated by Django 5.2.18 on 2026-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'verbose_name': '玩家資料', 'verbose_name_plural': '玩家資料'},
        ),
    ]
