# Generated by Django 5.2.18 on 2026-10-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('controls', models.TextField(blank=True, verbose_name='操作說明')),
                ('bundle_path', models.CharField(max_length=200)),
                ('adapter_path', models.CharField(max_length=200)),
                ('scratch_project_id', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('stage', '一般關卡'), ('boss', '魔王戰')], default='stage', max_length=10)),
                ('questions_required', models.PositiveSmallIntegerField(verbose_name='過關所需答對題數')),
                ('exp_reward', models.PositiveIntegerField(verbose_name='首次通關 EXP')),
                ('min_seconds', models.PositiveSmallIntegerField(default=5, verbose_name='合理的最短通關秒數')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='games.game')),
            ],
            options={
                'ordering': ['game', 'order'],
                'constraints': [models.UniqueConstraint(fields=('game', 'key'), name='level_unique_key_per_game'), models.UniqueConstraint(fields=('game', 'order'), name='level_unique_order_per_game'), models.CheckConstraint(condition=models.Q(('questions_required__gte', 1)), name='level_requires_question')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('number', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(db_index=True, max_length=20, verbose_name='文法主題')),
                ('context', models.CharField(blank=True, max_length=200, verbose_name='前導句')),
                ('prompt', models.CharField(max_length=200, verbose_name='題幹')),
                ('hint_zh', models.CharField(blank=True, max_length=200, verbose_name='中文提示')),
                ('correct_answer', models.CharField(max_length=40)),
                ('choices', models.JSONField(default=list)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game')),
            ],
            options={
                'ordering': ['game', 'number'],
                'constraints': [models.UniqueConstraint(fields=('game', 'key'), name='question_unique_key_per_game')],
            },
        ),
    ]
