# Generated by Django 5.2.18 on 2026-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='in_game',
            field=models.BooleanField(default=True, verbose_name='遊戲內題目'),
        ),
    ]
