# Generated by Django 5.2.18 on 2026-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_question_in_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '遊戲', 'verbose_name_plural': '遊戲'},
        ),
        migrations.AlterModelOptions(
            name='gamelevel',
            options={'ordering': ['game', 'order'], 'verbose_name': '關卡', 'verbose_name_plural': '關卡'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['game', 'number'], 'verbose_name': '題目', 'verbose_name_plural': '題目'},
        ),
    ]
