# Generated by Django 5.2.18 on 2026-10-08 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('level_clear', '通關獎勵'), ('adjustment', '管理員調整')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experience', to='learning.learningrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='exp_user_recent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='exp_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('reason', 'level_clear'), _negated=True), ('learning_record__isnull', False), _connector='OR'), name='exp_level_clear_has_record')],
            },
        ),
    ]
