# Generated by Django 5.2.18 on 2026-10-08 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('learning', '0002_reviewattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='experiencetransaction',
            name='ref',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='experiencetransaction',
            name='reason',
            field=models.CharField(choices=[('level_clear', '通關獎勵'), ('review', '錯題複習'), ('quest', '每日任務'), ('adjustment', '管理員調整')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='experiencetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('ref', ''), _negated=True), fields=('user', 'reason', 'ref'), name='exp_unique_ref_per_reason'),
        ),
        migrations.AddField(
            model_name='achievementunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='achievementunlock',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='achievement_unique_per_user'),
        ),
    ]
