# Generated by Django 5.2.18 on 2026-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_achievementunlock_experiencetransaction_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementunlock',
            options={'verbose_name': '成就解鎖', 'verbose_name_plural': '成就解鎖'},
        ),
        migrations.AlterModelOptions(
            name='experiencetransaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '經驗值紀錄', 'verbose_name_plural': '經驗值紀錄'},
        ),
    ]
